config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: { registrations: 'registrations' }
  resources :events, :invitations
  get '/creators/info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitation
  has_many :attendees, through: :invitation, source: :user

  scope :past, -> { where('start_date_time < ?', Time.zone.now) }
  scope :upcoming, -> { where('start_date_time >= ?', Time.zone.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event', dependent: :destroy
  has_many :invitation
  has_many :attended_event, through: :invitation, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name])
  end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  def info
    @created_events = current_user.created_events
    @past_events = current_user.attended_event.past
    @upcoming_events = current_user.attended_event.upcoming
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /events or /events.json
  def index
    @events = Event.all.order('created_at DESC')
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  # GET /events/1 or /events/1.json
  def show
    @invitation = Invitation.new
  end

  # GET /events/new
  def new
    @event = current_user.created_events.build
  end

  # GET /events/1/edit
  def edit; end

  # event /events or /events.json
  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def correct_user
    @event = current_user.created_events.find_by(id: params[:id])
    redirect_to events_path, alert: "You're not authorized to edit this event" if @event.nil?
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:creator_id, :title, :description, :location, :start_date_time, :end_date_time,
                                  :created_at)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1 or /invitations/1.json
  def show; end

  # POST /invitations or /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)
    isthere = Invitation.where('user_id= ? AND event_id= ?', @invitation.user_id, @invitation.event_id)
    if isthere.ids[0].nil?
      @invitation.save
      redirect_to events_path, notice: 'Invitation was successfully created.'
    else
      redirect_to events_path, notice: 'You Already in the list.'
    end
  end

  # DELETE /invitations/1 or /invitations/1.json
  def destroy
    @invitation.destroy
    redirect_to invitations_url, notice: 'Invitation was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invitation
    @invitation = Invitation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def invitation_params
    params.require(:invitation).permit(:user_id, :event_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/creators/events.html.erb
<h1>current_user.name 's Created Events</h1>
<div class="d-flex justify-content-between flex-wrap">
  <% @created_events.each do |event| %>
    <div class="card">
      <div class="card-header">
        <h4><%= event.name %></h4>
        <p><%= event.creator.name %></p>
      </div>
      <div class="card-body">
        <p><%= event.description %></p>
        <p><%= event.location %></p>
        <small><%= event.start_date_time %></small>
        <small><%= event.end_date_time %></small>

        <nav class="level">
          <div class="">
            <%= link_to event, class: "level-item" do %>
            <span class="icon">
              <i class="fa fa-link" aria-hidden="true"></i>
            </span>
          <% end %>
          <%= link_to edit_event_path(event), class: "level-item" do %>
          <span class="icon">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </span>
        <% end %>
        <%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
        <span class="icon">
          <i class="fa fa-trash" aria-hidden="true"></i>
        </span>
      <% end %>

    </div>
  </nav>
</div>

</div>
<% end %>

</div>

<h1>current_user.name 's Upcoming Events'</h1>
<div class="d-flex justify-content-between flex-wrap">
  <% @upcoming_events.each do |event| %>
    <div class="card">
      <div class="card-header">
        <h4><%= event.name %></h4>
        <p><%= event.creator.name %></p>
      </div>
      <div class="card-body">
        <p><%= event.description %></p>
        <p><%= event.location %></p>
        <small><%= event.start_date_time %></small>
        <small><%= event.end_date_time %></small>

        <nav class="level">
          <div class="">
            <%= link_to event, class: "level-item" do %>
            <span class="icon">
              <i class="fa fa-link" aria-hidden="true"></i>
            </span>
          <% end %>
          <%= link_to edit_event_path(event), class: "level-item" do %>
          <span class="icon">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </span>
        <% end %>
        <%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
        <span class="icon">
          <i class="fa fa-trash" aria-hidden="true"></i>
        </span>
      <% end %>

    </div>
  </nav>
</div>

</div>
<% end %>

</div>
<h1>current_user.name 's Past Events'</h1>
<div class="d-flex justify-content-between flex-wrap">
  <% @created_events.each do |event| %>
    <div class="card">
      <div class="card-header">
        <h4><%= event.name %></h4>
        <p><%= event.creator.name %></p>
      </div>
      <div class="card-body">
        <p><%= event.description %></p>
        <p><%= event.location %></p>
        <small><%= event.start_date_time %></small>
        <small><%= event.end_date_time %></small>

        <nav class="level">
          <div class="">
            <%= link_to event, class: "level-item" do %>
            <span class="icon">
              <i class="fa fa-link" aria-hidden="true"></i>
            </span>
          <% end %>
          <%= link_to edit_event_path(event), class: "level-item" do %>
          <span class="icon">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </span>
        <% end %>
        <%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
        <span class="icon">
          <i class="fa fa-trash" aria-hidden="true"></i>
        </span>
      <% end %>

    </div>
  </nav>
</div>

</div>
<% end %>

</div>

app/views/creators/info.html.erb
<section class="container-fluid text-center mx-auto my-4">
  <h1><%=current_user.name %>'s Created Events</h1>
  <div class="d-flex justify-content-around flex-wrap">
    <% @created_events.each do |event| %>
      <div class="card">
        <div class="card-header">
          <h4><%= event.title %></h4>
          <p><%= event.creator.name %></p>
        </div>
        <div class="card-body">
          <p><%= event.description %></p>
          <p><%= event.location %></p>
          <small><%= event.start_date_time %></small>
          <small><%= event.end_date_time %></small>

          <nav class="level">
            <div class="">
              <%= link_to event, class: "level-item" do %>
              <span class="icon">
                <i class="fa fa-link" aria-hidden="true"></i>
              </span>
            <% end %>
            <%= link_to edit_event_path(event), class: "level-item" do %>
            <span class="icon">
              <i class="fa fa-pencil" aria-hidden="true"></i>
            </span>
          <% end %>
          <%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
          <span class="icon">
            <i class="fa fa-trash" aria-hidden="true"></i>
          </span>
        <% end %>

      </div>
    </nav>
  </div>
</div>
<% end %>
</div>
</section>

<section class="container-fluid text-center mx-auto my-4">
<h1><%=current_user.name %>'s Upcoming Events</h1>
<div class="d-flex justify-content-around flex-wrap">
<% @upcoming_events.each do |event| %>
<div class="card">
  <div class="card-header">
    <h4><%= event.title %></h4>
    <p><%= event.creator.name %></p>
  </div>
  <div class="card-body">
    <p><%= event.description %></p>
    <p><%= event.location %></p>
    <small><%= event.start_date_time %></small>
    <small><%= event.end_date_time %></small>

    <nav class="level">
      <div class="">
        <%= link_to event, class: "level-item" do %>
        <span class="icon">
          <i class="fa fa-link" aria-hidden="true"></i>
        </span>
      <% end %>
      <%= link_to edit_event_path(event), class: "level-item" do %>
      <span class="icon">
        <i class="fa fa-pencil" aria-hidden="true"></i>
      </span>
    <% end %>
    <%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
    <span class="icon">
      <i class="fa fa-trash" aria-hidden="true"></i>
    </span>
  <% end %>
</div>
</nav>
</div>
</div>
<% end %>
</div>
</section>

<section class="container-fluid text-center mx-auto my-4">
<h1><%=current_user.name %>'s Past Events</h1>
<div class="d-flex justify-content-around flex-wrap">
<% @created_events.each do |event| %>
<div class="card">
<div class="card-header">
<h4><%= event.title %></h4>
<p><%= event.creator.name %></p>
</div>
<div class="card-body">
<p><%= event.description %></p>
<p><%= event.location %></p>
<small><%= event.start_date_time %></small>
<small><%= event.end_date_time %></small>
<nav class="level">
<div class="">
  <%= link_to event, class: "level-item" do %>
  <span class="icon">
    <i class="fa fa-link" aria-hidden="true"></i>
  </span>
<% end %>
<%= link_to edit_event_path(event), class: "level-item" do %>
<span class="icon">
  <i class="fa fa-pencil" aria-hidden="true"></i>
</span>
<% end %>
<%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
<span class="icon">
<i class="fa fa-trash" aria-hidden="true"></i>
</span>
<% end %>
</div>
</nav>
</div>
</div>
<% end %>
</div></section>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">

    <%= f.input :title, label: "Enter Event Title:", input_html: { class: "string"}, wrapper: false, label_html: { class: "label"}, placeholder: "compose a new event title...", autofocus: true %>
    <%= f.input :description, label: "Enter Event Description", input_html: { class: "text"}, wrapper: false, label_html: {class: "label"} %>
    <%= f.input :location, label: "Enter Event Location", input_html: { class: "string"}, wrapper: false, label_html: {class: "label"} %>
    <%= f.input :start_date_time, label: "Enter Event start date and time", input_html: { class: "datetime"}, wrapper: false, label_html: {class: "label"} %>
    <%= f.input :end_date_time, label: "Enter Event end date and time", input_html: { class: "datetime"}, wrapper: false, label_html: {class: "label"} %>
  </div>
</div>

<%= f.button :submit, class: "button bg-info" %>
<% end %>

app/views/events/_nav.html.erb
<div>

  <%= render(user_signed_in? ? '/layouts/signed_in_header' : '/layouts/signed_out_header') %>

</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<section class="section container-fluid text-center">
  <h1>Upcoming Events</h1>
  <div class="d-flex mx-auto justify-content-around flex-wrap">
    <% @upcoming_events.each do |event| %>
      <div class="card" style="width: 20rem">
        <div class="card-header">
          <h4><%= event.title %></h4>
          <p><%= event.creator.name %></p>
        </div>
        <div class="card-body">
          <p><%= event.description %></p>
          <p><%= event.location %></p>
          <small>
            <b>Starts:
            </b><%= event.start_date_time %></small>
          <br>
          <small>
            <b>Ends:
            </b><%= event.end_date_time %></small>

          <nav class="level">
            <div class="">
              <%= link_to event, class: "level-item" do %>
              <span class="icon">
                <i class="fa fa-link" aria-hidden="true"></i>
              </span>
            <% end %>
            <%= link_to edit_event_path(event), class: "level-item" do %>
            <span class="icon">
              <i class="fa fa-pencil" aria-hidden="true"></i>
            </span>
          <% end %>
          <%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
          <span class="icon">
            <i class="fa fa-trash" aria-hidden="true"></i>
          </span>
        <% end %>

      </div>
    </nav>
  </div>
</div>
<% end %>
</div>
</section>
<section class="section container-fluid text-center">
<h1>Past Events</h1>
<div class="d-flex mx-auto justify-content-around flex-wrap">
<% @past_events.each do |event| %>
<div class="card">
  <div class="card-header">
    <h4><%= event.title %></h4>
    <p><%= event.creator.name %></p>
  </div>
  <div class="card-body">
    <p><%= event.description %></p>
    <p><%= event.location %></p>
    <small>
      <b>Starts:
      </b><%= event.start_date_time %></small>
    <br>
    <small>
      <b>Ends:
      </b><%= event.end_date_time %></small>

    <nav class="level">
      <div class="">
        <%= link_to event, class: "level-item" do %>
        <span class="icon">
          <i class="fa fa-link" aria-hidden="true"></i>
        </span>
      <% end %>
      <%= link_to edit_event_path(event), class: "level-item" do %>
      <span class="icon">
        <i class="fa fa-pencil" aria-hidden="true"></i>
      </span>
    <% end %>
    <%= link_to event, method: :delete, data: {confirm: "Are you sure you want to delete this event?"} do %>
    <span class="icon">
      <i class="fa fa-trash" aria-hidden="true"></i>
    </span>
  <% end %>

</div>
</nav>
</div>
</div>
<% end %>
</div>
</section>
<div class="container-fluid mx-auto text-center">
<p>Create a New Event:
</p>
<%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<div class="section">
  <div class="container">
    <div class="row ">
      <div class="column">
        <h1 class="title">Creat a new Event</h1>
        <%= render "form", event: @event %>
      </div>
    </div>
  </div>
</div>
<nav class="navbar fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field ">
        <p class=" control">
          <%= link_to "Cancel", events_path, class: "button " %></p>
      </div>
    </div>
  </div>
</nav>

app/views/events/show.html.erb
<section class="container-fluid mx-auto text-center">
  <%= render(user_signed_in? ? '/layouts/signed_in_show' : '/layouts/signed_out_show') %>

</section>

app/views/layouts/_signed_in_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container-fluid ">
    <%= link_to 'Private Events', events_path,class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse  navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">

        <%= link_to current_user.email.split("@")[0],'/creators/info',class:'nav-link text-light'%>
        <%= link_to 'New Event', new_event_path,class:'nav-link text-light'%>
        <%= link_to 'Edit Account',edit_user_registration_path,class:'nav-link text-light'%>
        <%= link_to 'Log Out',destroy_user_session_path, method: :delete,class:'nav-link text-light'%>

      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_signed_in_show.html.erb
<section>

  <table class="mx-auto text-center table table-table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Location</th>
        <th>Start
        </th>
        <th>End
        </th>
        <th>Host</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @event.title %></td>
        <td><%= @event.location %></td>
        <td><%= @event.start_date_time %></td>
        <td><%= @event.end_date_time %></td>
        <td><%= @event.creator.name %></td>
        <td><%= @event.description %></td>
      </tr>
    </tbody>

  </table>

</section>
<section class="container-fluid mx-auto text-center">
  <h3>Attendees:</h3>
  <div class="">
    <% @event.attendees.each do |attendee| %>
      <p><%= attendee.name %></p>
    <% end %>
  </div>
</section>
<section class="container-fluid mx-auto text-center">
  <%= form_with(model: @invitation) do |form| %>
  <div class="field">
    <%= form.number_field :user_id, value:current_user.id , type: :hidden %>
  </div>
  <div class="field">
    <%= form.number_field :event_id, value:@event.id , type: :hidden %>
  </div>
  <div class="actions">
    <%= form.submit "Enroll", class: 'btn btn-primary' %>
  </div>
<% end %>

</section>

app/views/layouts/_signed_out_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container-fluid ">
    <%= link_to 'Private Events', events_path,class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse  navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">

        <%= link_to 'Sign In',new_user_session_path,class:'nav-link text-light'%>
        <%= link_to 'Sign Up',new_user_registration_path,class:'nav-link text-light'%>

      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_signed_out_show.html.erb
<section>

  <table class="mx-auto text-center table table-table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Location</th>
        <th>Start
        </th>
        <th>End
        </th>
        <th>Host</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @event.title %></td>
        <td><%= @event.location %></td>
        <td><%= @event.start_date_time %></td>
        <td><%= @event.end_date_time %></td>
        <td><%= @event.creator.name %></td>
        <td><%= @event.description %></td>
      </tr>
    </tbody>

  </table>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://pro.fontawesome.com/releases/v5.10.0/css/all.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="bg-primary">
        <p class='notice'>
          <%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="bg-danger">
        <p class='alert'>
          <%= alert %></p>
      </div>
    <% end %>
    <%= render '/events/nav/'%>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>